
/* Drop Tables */

DROP TABLE TB_PRODUCT_PRICE_QUJIAN;
DROP TABLE TB_PRODUCT_TYPE;




/* Create Tables */

CREATE TABLE TB_PRODUCT_PRICE_QUJIAN
(
	QUJIAN_ID VARCHAR2(20),
	START_NUM NUMBER,
	END_NUM NUMBER,
	PRICE NUMBER,
	PRODUCT_ID VARCHAR2(20) NOT NULL
);


CREATE TABLE TB_PRODUCT_TYPE
(
	PRODUCT_ID VARCHAR2(20) NOT NULL,
	PRODUCT_NAME VARCHAR2(200),
	PRODUCT_DESC VARCHAR2(2000),
	PRIMARY KEY (PRODUCT_ID)
);



/* Create Foreign Keys */

ALTER TABLE TB_PRODUCT_PRICE_QUJIAN
	ADD FOREIGN KEY (PRODUCT_ID)
	REFERENCES TB_PRODUCT_TYPE (PRODUCT_ID)
;



/* Comments */

COMMENT ON TABLE TB_PRODUCT_PRICE_QUJIAN IS '价格区间';
COMMENT ON COLUMN TB_PRODUCT_PRICE_QUJIAN.QUJIAN_ID IS '区间编号';
COMMENT ON COLUMN TB_PRODUCT_PRICE_QUJIAN.START_NUM IS '开始数量';
COMMENT ON COLUMN TB_PRODUCT_PRICE_QUJIAN.END_NUM IS '结束数量';
COMMENT ON COLUMN TB_PRODUCT_PRICE_QUJIAN.PRICE IS '价格';
COMMENT ON COLUMN TB_PRODUCT_PRICE_QUJIAN.PRODUCT_ID IS '产品编号';
COMMENT ON TABLE TB_PRODUCT_TYPE IS '产品分类';
COMMENT ON COLUMN TB_PRODUCT_TYPE.PRODUCT_ID IS '产品编号';
COMMENT ON COLUMN TB_PRODUCT_TYPE.PRODUCT_NAME IS '产品名称';
COMMENT ON COLUMN TB_PRODUCT_TYPE.PRODUCT_DESC IS '产品描述';



