
/* Drop Tables */

DROP TABLE T03_ARCHIVE_EDUCATION;
DROP TABLE T03_ARCHIVE_HOLIDAY;
DROP TABLE T03_ARCHIVE_JOB;
DROP TABLE T03_ARCHIVE_REWARD;
DROP TABLE T03_ARCHIVE_TRAIN;
DROP TABLE T03_ARCHIVE_INFO;




/* Create Tables */

CREATE TABLE T03_ARCHIVE_EDUCATION
(
	ID VARCHAR2(20),
	SCHOOL VARCHAR2(200),
	START_DATE DATE,
	END_DATE DATE,
	PROFESSION VARCHAR2(20),
	EDUCATION VARCHAR2(20),
	DEGREE_NAME VARCHAR2(20),
	ARCHIVE_ID VARCHAR2(20) NOT NULL
);


CREATE TABLE T03_ARCHIVE_HOLIDAY
(
	ID VARCHAR2(20),
	REASON VARCHAR2(2000),
	-- 1_事假；2_病假；3_年假；4_其他
	IS_TYPE VARCHAR2(2),
	START_DATE DATE,
	END_DATE DATE,
	ARCHIVE_ID VARCHAR2(20) NOT NULL
);


CREATE TABLE T03_ARCHIVE_INFO
(
	ARCHIVE_ID VARCHAR2(20) NOT NULL,
	USER_ID VARCHAR2(20),
	USER_NAME VARCHAR2(200),
	ORG_ID VARCHAR2(20),
	POSITION_NAME VARCHAR2(20),
	BIRTHDAY DATE,
	SEX VARCHAR2(2),
	NATONAL_NAME VARCHAR2(20),
	ZZMM VARCHAR2(20),
	TEL VARCHAR2(20),
	HOMETEL VARCHAR2(20),
	HOME_ADDR VARCHAR2(200),
	-- Base64编码
	PHOTO NCLOB,
	-- 0_无考核;1_20%;2_30%;3_50%;根据情况调整
	KHBZ VARCHAR2(2),
	-- OCP,PMP,系统集成等
	JOB_TITLE VARCHAR2(20),
	-- 0_在职；1_离职
	STATE VARCHAR2(2),
	PRIMARY KEY (ARCHIVE_ID)
);


CREATE TABLE T03_ARCHIVE_JOB
(
	ID VARCHAR2(20),
	COMPANY_NAME VARCHAR2(200),
	COMPANY_ADDR VARCHAR2(200),
	ADD_DATE DATE,
	LEAVE_DATE DATE,
	POSITION VARCHAR2(20),
	JOB_DES VARCHAR2(2000),
	LEAVE_REASON VARCHAR2(200),
	ARCHIVE_ID VARCHAR2(20) NOT NULL
);


CREATE TABLE T03_ARCHIVE_REWARD
(
	ID VARCHAR2(20),
	JF_REASON VARCHAR2(200),
	JF_DETAIL VARCHAR2(2000),
	-- 1_奖励；2_处罚
	JF_TYPE VARCHAR2(20),
	JF_DATE DATE,
	ARCHIVE_ID VARCHAR2(20) NOT NULL
);


CREATE TABLE T03_ARCHIVE_TRAIN
(
	ID VARCHAR2(20),
	SCHOOL VARCHAR2(200),
	TRAIN_DESC VARCHAR2(2000),
	START_DATE DATE,
	END_DATE DATE,
	ARCHIVE_ID VARCHAR2(20) NOT NULL
);



/* Comments */

COMMENT ON TABLE T03_ARCHIVE_EDUCATION IS '教育经历表';
COMMENT ON COLUMN T03_ARCHIVE_EDUCATION.ID IS '编号';
COMMENT ON COLUMN T03_ARCHIVE_EDUCATION.SCHOOL IS '培训学校';
COMMENT ON COLUMN T03_ARCHIVE_EDUCATION.START_DATE IS '入学时间';
COMMENT ON COLUMN T03_ARCHIVE_EDUCATION.END_DATE IS '毕业时间';
COMMENT ON COLUMN T03_ARCHIVE_EDUCATION.PROFESSION IS '专业';
COMMENT ON COLUMN T03_ARCHIVE_EDUCATION.EDUCATION IS '学历';
COMMENT ON COLUMN T03_ARCHIVE_EDUCATION.DEGREE_NAME IS '学位';
COMMENT ON COLUMN T03_ARCHIVE_EDUCATION.ARCHIVE_ID IS '档案编号';
COMMENT ON TABLE T03_ARCHIVE_HOLIDAY IS '年度休假情况表';
COMMENT ON COLUMN T03_ARCHIVE_HOLIDAY.ID IS '编号';
COMMENT ON COLUMN T03_ARCHIVE_HOLIDAY.REASON IS '休假原因';
COMMENT ON COLUMN T03_ARCHIVE_HOLIDAY.IS_TYPE IS '休假类型 : 1_事假；2_病假；3_年假；4_其他';
COMMENT ON COLUMN T03_ARCHIVE_HOLIDAY.START_DATE IS '开始时间';
COMMENT ON COLUMN T03_ARCHIVE_HOLIDAY.END_DATE IS '结束时间';
COMMENT ON COLUMN T03_ARCHIVE_HOLIDAY.ARCHIVE_ID IS '档案编号';
COMMENT ON TABLE T03_ARCHIVE_INFO IS '档案基本信息表';
COMMENT ON COLUMN T03_ARCHIVE_INFO.ARCHIVE_ID IS '档案编号';
COMMENT ON COLUMN T03_ARCHIVE_INFO.USER_ID IS '用户编号';
COMMENT ON COLUMN T03_ARCHIVE_INFO.USER_NAME IS '用户名称';
COMMENT ON COLUMN T03_ARCHIVE_INFO.ORG_ID IS '部门编号';
COMMENT ON COLUMN T03_ARCHIVE_INFO.POSITION_NAME IS '职位';
COMMENT ON COLUMN T03_ARCHIVE_INFO.BIRTHDAY IS '出生日期';
COMMENT ON COLUMN T03_ARCHIVE_INFO.SEX IS '性别';
COMMENT ON COLUMN T03_ARCHIVE_INFO.NATONAL_NAME IS '民族';
COMMENT ON COLUMN T03_ARCHIVE_INFO.ZZMM IS '政治面貌';
COMMENT ON COLUMN T03_ARCHIVE_INFO.TEL IS '个人电话';
COMMENT ON COLUMN T03_ARCHIVE_INFO.HOMETEL IS '家庭电话';
COMMENT ON COLUMN T03_ARCHIVE_INFO.HOME_ADDR IS '家庭地址';
COMMENT ON COLUMN T03_ARCHIVE_INFO.PHOTO IS '照片 : Base64编码';
COMMENT ON COLUMN T03_ARCHIVE_INFO.KHBZ IS '考核标志 : 0_无考核;1_20%;2_30%;3_50%;根据情况调整';
COMMENT ON COLUMN T03_ARCHIVE_INFO.JOB_TITLE IS '职称 : OCP,PMP,系统集成等';
COMMENT ON COLUMN T03_ARCHIVE_INFO.STATE IS '状态 : 0_在职；1_离职';
COMMENT ON TABLE T03_ARCHIVE_JOB IS '工作经历表';
COMMENT ON COLUMN T03_ARCHIVE_JOB.ID IS '编号';
COMMENT ON COLUMN T03_ARCHIVE_JOB.COMPANY_NAME IS '公司名称';
COMMENT ON COLUMN T03_ARCHIVE_JOB.COMPANY_ADDR IS '公司地址';
COMMENT ON COLUMN T03_ARCHIVE_JOB.ADD_DATE IS '入职时间';
COMMENT ON COLUMN T03_ARCHIVE_JOB.LEAVE_DATE IS '离职时间';
COMMENT ON COLUMN T03_ARCHIVE_JOB.POSITION IS '职位';
COMMENT ON COLUMN T03_ARCHIVE_JOB.JOB_DES IS '工作职责';
COMMENT ON COLUMN T03_ARCHIVE_JOB.LEAVE_REASON IS '离职原因';
COMMENT ON COLUMN T03_ARCHIVE_JOB.ARCHIVE_ID IS '档案编号';
COMMENT ON TABLE T03_ARCHIVE_REWARD IS '奖罚情况表';
COMMENT ON COLUMN T03_ARCHIVE_REWARD.ID IS '编号';
COMMENT ON COLUMN T03_ARCHIVE_REWARD.JF_REASON IS '奖罚原因';
COMMENT ON COLUMN T03_ARCHIVE_REWARD.JF_DETAIL IS '奖罚明细';
COMMENT ON COLUMN T03_ARCHIVE_REWARD.JF_TYPE IS '奖罚分类 : 1_奖励；2_处罚';
COMMENT ON COLUMN T03_ARCHIVE_REWARD.JF_DATE IS '奖罚时间';
COMMENT ON COLUMN T03_ARCHIVE_REWARD.ARCHIVE_ID IS '档案编号';
COMMENT ON TABLE T03_ARCHIVE_TRAIN IS '培训经历表';
COMMENT ON COLUMN T03_ARCHIVE_TRAIN.ID IS '编号';
COMMENT ON COLUMN T03_ARCHIVE_TRAIN.SCHOOL IS '培训学校';
COMMENT ON COLUMN T03_ARCHIVE_TRAIN.TRAIN_DESC IS '培训内容';
COMMENT ON COLUMN T03_ARCHIVE_TRAIN.START_DATE IS '入学时间';
COMMENT ON COLUMN T03_ARCHIVE_TRAIN.END_DATE IS '毕业时间';
COMMENT ON COLUMN T03_ARCHIVE_TRAIN.ARCHIVE_ID IS '档案编号';



